# -*- coding: utf-8 -*-
"""Ego_path.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLJFDXXZtflNGCfRamuKBNL9pMdvPVTO
"""

!git clone https://github.com/irtrailenium/train-ego-path-detection.git

cd train-ego-path-detection

pip install -r requirements.txt

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
import zipfile

print("="*60)
print("📁 COPYING AND EXTRACTING FILES FROM GOOGLE DRIVE")
print("="*60)

# Source files in Drive
DRIVE_BASE = "/content/drive/MyDrive/"
REPO_ZIP = f"{DRIVE_BASE}train-ego-path-detection.zip"
WEIGHTS_ZIP = f"{DRIVE_BASE}egopath.zip"

# Destination in Colab
COLAB_FOLDER = "/content/train-ego-path-detection"

# Remove existing folder if present
if os.path.exists(COLAB_FOLDER):
    shutil.rmtree(COLAB_FOLDER)
    print("   Removed old folder")

# Step 1: Extract the repository
print("\n📦 Extracting train-ego-path-detection.zip...")
with zipfile.ZipFile(REPO_ZIP, 'r') as zip_ref:
    zip_ref.extractall("/content")
print("✅ Repository extracted!")

# Check if the extracted folder has a different name
extracted_folders = [f for f in os.listdir("/content") if os.path.isdir(os.path.join("/content", f))]
for f in extracted_folders:
    if 'ego' in f.lower() or 'train' in f.lower():
        print(f"   Found: {f}")

# Step 2: Rename if needed
if os.path.exists("/content/train-ego-path-detection-main"):
    os.rename("/content/train-ego-path-detection-main", "/content/train-ego-path-detection")
    print("✅ Renamed to: train-ego-path-detection")

# Step 3: Extract weights
print("\n📦 Extracting egopath.zip...")
if os.path.exists(WEIGHTS_ZIP):
    with zipfile.ZipFile(WEIGHTS_ZIP, 'r') as zip_ref:
        zip_ref.extractall("/content")
    print("✅ Weights extracted!")
else:
    print("❌ egopath.zip not found!")

import os

print("="*60)
print("📂 CHECKING EXTRACTED FILES")
print("="*60)

# Check what's in /content
print("\n📁 Contents of /content:")
for item in os.listdir('/content'):
    item_path = os.path.join('/content', item)
    if os.path.isdir(item_path):
        print(f"   📁 {item}/")
        # Show what's inside
        for sub in os.listdir(item_path):
            sub_path = os.path.join(item_path, sub)
            if os.path.isdir(sub_path):
                print(f"      📁 {sub}/")
            else:
                size = os.path.getsize(sub_path) / (1024*1024)
                print(f"      📄 {sub} ({size:.2f} MB)")
    else:
        size = os.path.getsize(item_path) / (1024*1024)
        print(f"   📄 {item} ({size:.2f} MB)")

import os
import shutil
import glob

print("="*60)
print("📂 ORGANIZING FILES")
print("="*60)

# Find the extracted ego path folder
repo_folder = None
for item in os.listdir('/content'):
    if os.path.isdir(os.path.join('/content', item)):
        if 'ego' in item.lower() or 'train' in item.lower():
            if 'zip' not in item:
                repo_folder = os.path.join('/content', item)
                print(f"✅ Found repository folder: {repo_folder}")
                break

# Find the extracted weights folder
weights_source = None
for root, dirs, files in os.walk('/content'):
    for dir_name in dirs:
        if dir_name == 'weights' and 'ego' not in root:
            weights_source = os.path.join(root, dir_name)
            print(f"✅ Found weights folder: {weights_source}")
            break
    if weights_source:
        break

# If we found both, copy weights into repository
if repo_folder and weights_source:
    # Create weights folder in repository
    dest_weights = os.path.join(repo_folder, 'weights')
    os.makedirs(dest_weights, exist_ok=True)

    # Copy all .pt files
    for file in os.listdir(weights_source):
        src = os.path.join(weights_source, file)
        dst = os.path.join(dest_weights, file)
        if os.path.isfile(src):
            shutil.copy(src, dst)
            print(f"   Copied: {file}")

    print(f"✅ Weights copied to: {dest_weights}")

    # Set the repo path
    repo_path = repo_folder
else:
    # If we couldn't find weights, check if they are already in the repo
    repo_path = "/content/train-ego-path-detection"
    if os.path.exists(repo_path):
        weights_path = os.path.join(repo_path, 'weights')
        if os.path.exists(weights_path):
            print(f"✅ Weights already in: {weights_path}")
            repo_path = repo_path
        else:
            print("❌ Could not find weights folder")
            print("📤 Please upload your best.pt file manually:")
            from google.colab import files
            uploaded = files.upload()
            os.makedirs(weights_path, exist_ok=True)
            for fname in uploaded.keys():
                shutil.move(f'/content/{fname}', f'{weights_path}/best.pt')
                print(f"✅ Uploaded: {fname}")

from google.colab import drive
drive.mount('/content/drive')

# Unzip the file and extract everything into your Colab environment
!unzip /content/drive/MyDrive/train-ego-path-detection.zip -d /content/train-ego-path-detection

import os
import shutil

print("="*60)
print("📂 FIXING NESTED FOLDER STRUCTURE")
print("="*60)

# The nested folder path
nested_path = "/content/train-ego-path-detection/train-ego-path-detection"

if os.path.exists(nested_path):
    print(f"✅ Found nested folder: {nested_path}")

    # Move all contents to the parent folder
    for item in os.listdir(nested_path):
        src = os.path.join(nested_path, item)
        dst = os.path.join("/content/train-ego-path-detection", item)

        # Remove destination if it exists
        if os.path.exists(dst):
            if os.path.isdir(dst):
                shutil.rmtree(dst)
            else:
                os.remove(dst)

        shutil.move(src, dst)
        print(f"   Moved: {item}")

    # Remove the now-empty nested folder
    shutil.rmtree(nested_path)
    print("✅ Removed nested folder")
else:
    print("❌ No nested folder found")

import os

print("="*60)
print("📂 VERIFYING FIXED STRUCTURE")
print("="*60)

repo_path = "/content/train-ego-path-detection"

if os.path.exists(repo_path):
    print(f"✅ Repository at: {repo_path}")
    print("\n📁 Contents:")
    for item in os.listdir(repo_path):
        item_path = os.path.join(repo_path, item)
        if os.path.isdir(item_path):
            print(f"   📁 {item}/")
            # Check if it's a weights subfolder
            if item == "weights":
                for sub in os.listdir(item_path):
                    sub_path = os.path.join(item_path, sub)
                    if os.path.isdir(sub_path):
                        print(f"      📁 {sub}/")
                        # Show contents of each model folder
                        for file in os.listdir(sub_path):
                            file_path = os.path.join(sub_path, file)
                            size = os.path.getsize(file_path) / (1024*1024)
                            print(f"         📄 {file} ({size:.2f} MB)")
        else:
            print(f"   📄 {item}")
else:
    print("❌ Repository not found!")

# Commented out IPython magic to ensure Python compatibility.


# %cd /content/train-ego-path-detection

import os
import sys
import cv2
import glob
import shutil
from google.colab.patches import cv2_imshow
from google.colab import files

print("="*60)
print("🔍 SENTRA - EGO-PATH DETECTION")
print("="*60)

# STEP 1: Upload image
print("\n📤 Upload railway track image:")
uploaded = files.upload()

# STEP 2: Find the uploaded file
original_name = list(uploaded.keys())[0]
print(f"📷 Uploaded: {original_name}")

# Search for the file (it might be in /content/ or /content/train-ego-path-detection/)
import glob
found_files = glob.glob(f'/content/**/{original_name}', recursive=True)
if not found_files:
    found_files = glob.glob(f'/content/**/*{original_name}*', recursive=True)

if not found_files:
    print("❌ File not found!")
    exit()

img_path = found_files[0]
img_name = os.path.basename(img_path)
print(f"📷 Using: {img_path}")

# STEP 3: Model
model_folder = "/content/train-ego-path-detection/weights/chromatic-laughter-5"

if not os.path.exists(model_folder):
    print(f"❌ Model not found: {model_folder}")
    print("\n📂 Available models:")
    for item in os.listdir("/content/train-ego-path-detection/weights"):
        if os.path.isdir(os.path.join("/content/train-ego-path-detection/weights", item)):
            print(f"   - {item}")
    exit()

print(f"✅ Using model: chromatic-laughter-5")

# STEP 4: Run detection
!mkdir -p /content/output
print(f"\n🔍 Processing: {img_name}")

# Use subprocess to handle paths properly
import subprocess
cmd = [
    "python", "detect.py",
    model_folder,
    img_path,
    "--output", "/content/output"
]

result = subprocess.run(cmd, capture_output=True, text=True, cwd="/content/train-ego-path-detection")

if result.stderr:
    print("⚠️ Errors:", result.stderr)

# STEP 5: Show results
print("\n📊 RESULTS:")
output_files = glob.glob('/content/output/*.jpg')
if output_files:
    for out_file in output_files:
        img = cv2.imread(out_file)
        if img is not None:
            print(f"✅ Output: {out_file}")
            cv2_imshow(img)
else:
    print("❌ No output generated")
    print("\n📂 Output folder contents:")
    !ls -la /content/output



# Check if your models still exist
import os

print("="*60)
print("🔍 CHECKING FOR MODELS IN CURRENT SESSION")
print("="*60)

# Check YOLO model
if os.path.exists("/content/runs/detect/train-2/weights/best.pt"):
    print("✅ YOLO model found at: /content/best.pt")
else:
    print("❌ YOLO model NOT found")

# Check Ego-Path model
if os.path.exists('/content/train-ego-path-detection/weights/chromatic-laughter-5/best.pt'):
    print("✅ Ego-Path model found")
else:
    print("❌ Ego-Path model NOT found")

from google.colab import files

# Download YOLO model
if os.path.exists("/content/runs/detect/train-2/weights/best.pt"):
    files.download("/content/runs/detect/train-2/weights/best.pt")
    print("✅ Downloaded: YOLO best.pt")

# Download Ego-Path model
ego_path = '/content/train-ego-path-detection/weights/chromatic-laughter-5/best.pt'
if os.path.exists(ego_path):
    files.download(ego_path)
    print("✅ Downloaded: Ego-Path best.pt")