# -*- coding: utf-8 -*-
"""Obstacle detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfK2JGy7Ip7rr5goxVhYqbPlaUL7mtza
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8m.yaml")   # This downloads pretrained model

!ls /content

!unzip -o /content/mainf.zip -d /content/dataset

!ls -lh /content

model = YOLO("yolov8m.pt")

model.train(
    data="/content/dataset/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    device=0
)

from ultralytics import YOLO



model.predict(
    source="/content/dataset/test/images",
    save=True,
    conf=0.25
)

!ls /content/runs/detect

!ls /content/runs/detect/train-2/weights

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train-2/weights/best.pt")

metrics = model.val()
print(metrics)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train-2/weights/best.pt")

results = model.predict(
    source="/content/dataset/test/images",
    conf=0.15,
    save=True
)

from ultralytics import YOLO
from google.colab.patches import cv2_imshow
import cv2

# Load your trained model
model = YOLO("/content/runs/detect/train-2/weights/best.pt")

# Path to the image you want to test
image_path = "/content/dataset/test/images/Animal-Obstacle-110-_jpg.rf.ad3cd0a4bb68ccbbef123f9b6d583780.jpg"

# Run prediction
results = model.predict(
    source=image_path,
    conf=0.25,        # Confidence threshold
    save=True,        # Save the result
    show_labels=True, # Show class names
    show_conf=True    # Show confidence scores
)

# Display the result
for r in results:
    img = r.plot()  # Get image with bounding boxes
    cv2_imshow(img) # Show the image

# Check if your models still exist
import os

print("="*60)
print("🔍 CHECKING FOR MODELS IN CURRENT SESSION")
print("="*60)

# Check YOLO model
if os.path.exists("/content/runs/detect/train-2/weights/best.pt"):
    print("✅ YOLO model found at: /content/best.pt")
else:
    print("❌ YOLO model NOT found")

# Check Ego-Path model
if os.path.exists('/content/train-ego-path-detection/weights/chromatic-laughter-5/best.pt'):
    print("✅ Ego-Path model found")
else:
    print("❌ Ego-Path model NOT found")

from google.colab import files

# Download YOLO model
if os.path.exists("/content/runs/detect/train-2/weights/best.pt"):
    files.download("/content/runs/detect/train-2/weights/best.pt")
    print("✅ Downloaded: YOLO best.pt")

# Download Ego-Path model
ego_path = '/content/train-ego-path-detection/weights/chromatic-laughter-5/best.pt'
if os.path.exists(ego_path):
    files.download(ego_path)
    print("✅ Downloaded: Ego-Path best.pt")

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil

print("="*60)
print("💾 SAVING MODELS TO GOOGLE DRIVE (PERMANENT)")
print("="*60)

# Create folder in Drive
save_folder = "/content/drive/MyDrive/SENTRA_Models"
os.makedirs(save_folder, exist_ok=True)

# Save YOLO model
if os.path.exists('/content/best.pt'):
    shutil.copy('/content/best.pt', f'{save_folder}/yolo_best.pt')
    print("✅ Saved: yolo_best.pt")

# Save Ego-Path model
ego_path = '/content/train-ego-path-detection/weights/chromatic-laughter-5/best.pt'
if os.path.exists(ego_path):
    shutil.copy(ego_path, f'{save_folder}/ego_path_best.pt')
    print("✅ Saved: ego_path_best.pt")

    # Also save config
    config_path = '/content/train-ego-path-detection/weights/chromatic-laughter-5/config.yaml'
    if os.path.exists(config_path):
        shutil.copy(config_path, f'{save_folder}/ego_path_config.yaml')
        print("✅ Saved: ego_path_config.yaml")

print(f"\n✅ All models saved to: {save_folder}")
print("\n📁 Files in Drive:")
!ls -la "/content/drive/MyDrive/SENTRA_Models/"